name: Node CI

on:
#  schedule:
#    - cron: '0 0 * * *'
 push:
   branches:
     - master
  # release:
  #   types: [created,edited]

jobs:
  listify-auto:
    runs-on: ubuntu-latest
    name: listify auto
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: listify action step
      uses: ifuture-pro/listify-actions
      with:
        listify: ./ --exclude='^_\S*' --package --exclude_dir=draft
        github_token: ${{ secrets.GH_TOKEN }}
